name: Rewrite Web IDL and submit the results

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#5_8_*_*_1
    - cron: "5 8 * * 1"

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run rewrite
      - run: npm run submit-pullrequest
        env:
          # Intentionally not using GITHUB_TOKEN.
          # GH_TOKEN will use @autokagami for creating PRs.
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
